name: weather_counter_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^2.0.0
  flutter_riverpod: ^2.3.2
  shared_preferences: ^2.0.18
  dio: ^5.0.3
  json_annotation: ^4.8.0
  retry: ^3.1.0
  connectivity_plus: ^3.0.3
  fluttertoast: ^8.2.1


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1


  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  